version: "2"

services:
  sonarqube:
    image: sonarqube:8.9-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /opt/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /opt/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /opt/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - /opt/sonarqube/sonarqube_temp:/opt/sonarqube/temp
  db:
    image: postgres:13.3
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /opt/sonarqube/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - /opt/sonarqube/postgresql/data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge